//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectEstimation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class projectDetail
    {
        public int sno { get; set; }
        public string projectName { get; set; }
        public string devActivityHours { get; set; }
        public string Employee { get; set; }
    }
}
