//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectEstimation.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class projectEstimatorEntities : DbContext
    {
        public projectEstimatorEntities()
            : base("name=projectEstimatorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<projectDetail> projectDetails { get; set; }
        public virtual DbSet<newProject> newProjects { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
